### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by blue-9**
Maybe the type.

Please review!

### CODE REVIEW

**Comment by benswift** [comment]
Thanks. I don't suppose you've got any js experience? If so then [this issue](https://github.com/extemporelang/highlight.js/issues/1) is probably the best bang-for-buck contribution to the docs at the moment. But I realise it's an "out-of-band" issue 🙂

**Comment by cyblue9** [comment]
Thank for merge!😁

> If so then this issue is probably the best bang-for-buck contribution to the docs at the moment.

Oh, It's a very exciting problem!!!

I tried it.(https://github.com/highlightjs/highlight.js/pull/1902)

example:

xtlang code
```lisp
(bind-func xtlang_closure
  (lambda (c:double d:i64)
    (let ((result (* c (i64tod d))))
      (printf "result = %f\n" result)
      result)))

(xtlang_closure 4.5 2) ;; prints "result = 9.000000", returns 9.0
```
after parse
```XHTML
(<span class="hljs-keyword">bind-func <span class="hljs-title">xtlang_closure</span></span>
  (<span class="hljs-keyword">lambda</span> (<span class="hljs-variable">c</span><span class="hljs-type">:double</span> <span class="hljs-variable">d</span><span class="hljs-type">:i64</span>)
    (<span class="hljs-keyword">let</span> ((<span class="hljs-variable">result</span> (<span class="hljs-funciton">*</span> <span class="hljs-variable">c</span> (<span class="hljs-funciton">i64tod</span> <span class="hljs-variable">d</span>))))
      (<span class="hljs-funciton">printf</span> <span class="hljs-string">"result = %f\n"</span> <span class="hljs-variable">result</span>)
      <span class="hljs-variable">result</span>)))

(<span class="hljs-variable">xtlang_closure</span> <span class="hljs-number">4.5</span> <span class="hljs-number">2</span>) <span class="hljs-comment">;; prints "result = 9.000000", returns 9.0</span>
```

I implemented it so that it behaves like the  [Pygments](https://bitbucket.org/birkenfeld/pygments-main/src/7941677dc77d4f2bf0bbd6140ade85a9454b8b80/pygments/lexers/lisp.py?at=default&fileviewer=file-view-default#lisp.py-2420).

I confirmed the [```tests/core/xtlang.xtm```](https://github.com/digego/extempore/blob/master/tests/core/xtlang.xtm#L1314) , but there was no problem.  Everything is OK!😊

Is the output XHTML tag right?

**Comment by benswift** [comment]
Great, thanks. Seems ok - there are always edge cases with this sort of thing, but we can catch them as they come up. Hopefully it's not too much trouble to get it to land upstream.

Thanks very much 👍

**Comment by cyblue9** [comment]
@benswift 
Thank for review and advice!

**Comment by benswift** [comment]
no worries

**Pull request merged**
